include:
  - template: Auto-DevOps.gitlab-ci.yml

production:
  stage: production
  script:
    - echo "Deploy to production"
  environment:
    name: production
    url: https://jsvcycling.com
  only:
    - master
