include:
  - template: Auto-DevOps.gitlab-ci.yml

production:
<<: *production_template
environment:
  name: production
  url: https://jsvcycling.com
only:
  refs:
    - master
  kubernetes: active
except:
  variables:
    - $STAGING_ENABLED
    - $CANARY_ENABLED
    - $INCREMENTAL_ROLLOUT_ENABLED
    - $INCREMENTAL_ROLLOUT_MODE
