baseURL = "https://jsvcycling.com/"
languageCode = "en-US"
title = "Joshua Vega"
copyright = "2019-2022 Joshua Vega. All Rights Reserved."

disableKinds = ["taxonomy", "term"]

[markup.highlight]
codeFences = false
style = "borland"

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Joshua Vega"
description = "The personal website of Joshua Vega."
mainSections = ["posts"]

[permalinks]
posts = "/posts/:year/:month/:slug"

[blackfriday]
hrefTargetBlank = true
