baseURL = "https://jsvcycling.com/"
languageCode = "en-us"
title = "Joshua Vega's Blog"
copyright = "2019 Joshua Vega. All Rights Reserved."

[params]
author = "Joshua Vega"
description = "The personal website of Joshua Vega."
tagline = "I write code and stuff..."
mainSections = ["posts"]

[permalinks]
posts = "/posts/:year/:month/:slug"

[[menu.main]]
identifier = "home"
name = "Home"
title = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "curriculum-vitae"
name = "Curriculum Vitae"
title = "Curriculum Vitae"
url = "/curriculum-vitae"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
title = "About"
url = "/about"
weight = 3