baseURL = "https://jsvcycling.com/"
languageCode = "en-us"
title = "Joshua Vega's Blog"
copyright = "2019 Joshua Vega. All Rights Reserved."
pygmentsCodeFences = true
pygmentsStyle = "pygments"
pygmentsOptions="linenos=table"

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Joshua Vega"
description = "The personal website of Joshua Vega."
tagline = "I write code and stuff..."
mainSections = ["posts"]

[permalinks]
posts = "/posts/:year/:month/:slug"

[blackfriday]
hrefTargetBlank = true

[[menu.main]]
identifier = "home"
name = "Home"
title = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "curriculum-vitae"
name = "Curriculum Vitae"
title = "Curriculum Vitae"
url = "/curriculum-vitae/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
title = "About"
url = "/about/"
weight = 3

[[menu.social]]
identifier = "github"
name = "GitHub"
title = "GitHub"
url = "https://github.com/jsvcycling"

[[menu.social]]
identifier = "gitlab"
name = "GitLab"
title = "GitLab"
url = "https://gitlab.com/jsvcycling"

[[menu.social]]
identifier = "twitter"
name = "Twitter"
title = "Twitter"
url = "https://twitter.com/jsvcycling"